#spring.application.name=crudStudent
#server.port=8080
#spring.datasource.url=jdbc:h2:mem:studentcrud
#spring.datasource.username=root
#spring.datasource.password=12345678
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/curdstudent
spring.datasource.username=root
spring.datasource.password=Ajay@2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true