spring.application.name=curdstudent
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/curdstudent
spring.datasource.username=root
spring.datasource.password=Ajay@2001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true